### ISSUE TITLE
Question about progress; possible help; and donations.

### ISSUE THREAD

**Issue by laserstrike** [phhusson/Superuser#40]
Would you be interested in defining a list of all the todos necessary to have a complete viable alternative to supersu? I mean including the latest versions of android. I see that there is a flashable zip (http://superuser.phh.me/) here. But I'm not sure if that includes 6.0.1, etc.

Of course there is a lot of interest, and I'm not sure how you feel about this but there is also a lot of interest in donating to such a cause. That is why I ask if you could define these so they can be put on bountysource, according to this (https://www.reddit.com/r/linux/comments/3myp1r/why_the_hell_android_community_support_a/) there are many who are willing to help financially. Though, I guess, it isn't just helping you financially but also getting those with expertise to help you as there are some who don't wanna do it for free. 

The overall goal  to make it as easy as a universal flashable zip, and keeping the superuser apk updated from time to time, maybe a lot to ask, so maybe all the help and incentive that one could put on the table would be best? I apologize if this is seems uninformed or pushy, but I'm very interested in supporting open source projects, and for those for which I know little about, I guess the best I can do is to bring more awareness to it.

Thanks for reading.

**Comment by phhusson** [comment]
Hi,

For Android >= 6.0, the "su" binary itself is not enough.
Some modifications in the boot.img are needed, and some SELinux editing.
So it is now spread to https://github.com/phhusson/super-bootimg and
https://github.com/phhusson/sepolicy-inject

The results of those three projects is there:
https://superuser.phh.me/
There are two things:
- a rather general superuser.zip
- boot.img for 'widely' known devices

Obviously there are many things left to do, but this is a usable solution
on modern Android (and actually my SU was available before SuperSU on N
preview).

Also, I had in my ambitions to write proper SELinux rules, so that having
SU remains safe, and also without disabling dm-verity. This is a tough
work, so I don't really match those ambitions.

At the moment, what is really needed is work on the application itself.
It is nothing highly technical, anyone into Android application development
can do it.
But I really don't feel like it, I prefer spending time on the low-level
stuff, so I'd really like to have someone take care of the application.

As for bounties, I'm not too sure. Problem is that most of the work would
be mostly hidden.
For the app, it will be mostly a lot of cleanups and refreshning, so
nothing really bounty-able.
For the low-level, I'm expecting bounties would be device-focused, which is
totally wrong, because for most devices there will be little to no work
needed.
The low-level work needed is mostly around having OTA working (both for SU
itself and for the stock ROM), and supporting new apps (thoguh it's long
time I have not received incompatibility reports)
Possibly some new features needs will raise, like implementing rc.d-like
system, and more powerful bind mount


2016-04-20 0:11 GMT+02:00 laserstrike <notifications@github.com>:
